### ISSUE TITLE
setIsPlatformLoaded(true) called before platform is actually loaded

### ISSUE THREAD

**Issue by eigood** [narinluangrath/react-gapi-auth2#1]
https://github.com/narinluangrath/react-gapi-auth2/blob/829f87e900ff2110e7e2d072d0c7064062da5af6/src/GApiProvider.tsx#L71

When calling loadGooglePlatform, the first argument is 'onLoad', which is then attached to the generated <script> tag.  That's good.  However, the linked line just force-calls setIsPlatformLoaded(true), and then the secondary useEffect runs *immediately*, before the gapi has been loaded.  I then get a null pointer on window.gapi.load.

The fix just needs to delete the linked line.

**Comment by narinluangrath** [comment]
Thanks for the find @eigood! Fixed in 1.0.4
